=== AlainCouthures/xsltforms/testsuite/XForms1.1/Edition1/driverPages/xml/XF11TestSuite.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
            elementFormDefault="qualified" 
            attributeFormDefault="unqualified"
            targetNamespace="http://www.w3c.org/MarkUp/Forms/XForms/Test/11"
            xmlns="http://www.w3c.org/MarkUp/Forms/XForms/Test/11">

	<xsd:element name="testSuite" type="TestSuiteRecordType"/>     

	<xsd:complexType name="TestSuiteRecordType">
		<xsd:sequence minOccurs="0" maxOccurs="unbounded">
			<xsd:element name="specChapter" type="testCaseType" minOccurs="0" maxOccurs="unbounded"/>	
		</xsd:sequence>
		<xsd:attribute name="specVersion" />
	</xsd:complexType>

	<xsd:complexType name="testCaseType">
	    <xsd:sequence>
		    <xsd:element name="statusSummary" type="statusSummaryType"/>
            <xsd:element name="profile" type="testExecutionProfileType"/>
            <xsd:element name="testCase" type="testCaseDetailsType" minOccurs="1" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="chapterName" use="required"/>
		<xsd:attribute name="productId" />	
        <xsd:attribute name="chapterTitle" use="required"/>	
	</xsd:complexType>
    
    <xsd:complexType name="testExecutionProfileType">
       <xsd:sequence>
          <xsd:element name="specification" type="specificationsType"/>
          <xsd:element name="normativeOnly" type="xsd:boolean"/>
          <xsd:element name="basicOnly" type="xsd:boolean"/>
       </xsd:sequence>
   </xsd:complexType>
     
     <xsd:simpleType name="specificationsType">
       <xsd:restriction base="xsd:string">
        <xsd:enumeration value="XForms 1.0"/>
        <xsd:enumeration value="XForms 1.1"/>
       </xsd:restriction>
     </xsd:simpleType>
     
     <xsd:simpleType name="specificationNumberType">
       <xsd:restriction base="xsd:string">
        <xsd:enumeration value="1.0"/>
        <xsd:enumeration value="1.1"/>
       </xsd:restriction>
     </xsd:simpleType>
	
	<xsd:complexType name="statusSummaryType">
	   <xsd:sequence minOccurs="0" maxOccurs="1">

		  <!-- Normative -->
		  <xsd:element name="numNormTotal" type="xsd:integer" default="0" minOccurs="0"/>
		  <xsd:element name="numNormPass" type="xsd:integer" default="0" minOccurs="0"/>
		  <xsd:element name="numNormFail" type="xsd:integer" default="0" minOccurs="0"/>
		  <xsd:element name="numNormUnknown" type="xsd:integer" default="0" minOccurs="0"/>
		  
		  <!-- Basic -->
		  <xsd:element name="numBasicTotal" type="xsd:integer" default="0" minOccurs="0"/>
		  <xsd:element name="numBasicPass" type="xsd:integer" default="0" minOccurs="0"/>
		  <xsd:element name="numBasicFail" type="xsd:integer" default="0" minOccurs="0"/>
		  <xsd:element name="numBasicUnknown" type="xsd:integer" default="0" minOccurs="0"/>

          <!-- XForms 1.0 -->
          <!--
          <xsd:element name="numXForms10Total" type="xsd:integer" default="0" minOccurs="0"/>
          <xsd:element name="numXForms10Pass" type="xsd:integer" default="0" minOccurs="0"/>
          <xsd:element name="numXForms10Fail" type="xsd:integer" default="0" minOccurs="0"/>
          <xsd:element name="numXForms10Unknown" type="xsd:integer" default="0" minOccurs="0"/>
		  -->
			
          <!-- XForms 1.1 -->
          <!--
          <xsd:element name="numXForms11Total" type="xsd:integer" default="0" minOccurs="0"/>
          <xsd:element name="numXForms11Pass" type="xsd:integer" default="0" minOccurs="0"/>
          <xsd:element name="numXForms11Fail" type="xsd:integer" default="0" minOccurs="0"/>
          <xsd:element name="numXForms11Unknown" type="xsd:integer" default="0" minOccurs="0"/>
 		  -->
 		  
	   </xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="testCaseDetailsType">
		<xsd:sequence>
       <!-- <xsd:element name="testCaseSpecification" type="specificationNumberType"/> -->
			<xsd:element name="testCaseSection" type="xsd:string"/>
			<xsd:element name="testCaseName" type="xsd:string"/>
			<xsd:element name="testCaseLink" type="xsd:anyURI"/>
			<xsd:element name="testCaseDescription" type="xsd:string"/>
			<xsd:element name="testCaseSpecLinkName" type="xsd:string"/>			
			<xsd:element name="testCaseSpecLink" type="xsd:anyURI"/>			
			<xsd:element name="testCaseBasic" type="xsd:boolean"/>
			<xsd:element name="testCaseNormative" type="xsd:boolean"/>
			<xsd:element name="testCaseStatus" type="testCaseStatusType"/>			
			<xsd:element name="testCaseDate" type="xsd:date"/>	
			<xsd:element name="testCaseRequired" type="xsd:boolean"/>
			<xsd:element name="testCaseNote" type="xsd:string"/>
       <!-- <xsd:element name="testCaseApplicability" type="testCaseApplicabilityType"/> -->
            <xsd:element name="relatedto" type="relatedToType" minOccurs="0"/>
            <xsd:element name="testSuiteUpdateInfo" type="testSuiteUpdateInfoType" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
    
    <xsd:complexType name="testSuiteUpdateInfoType">
        <xsd:sequence>
            <xsd:element name="suite">
               <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="insertionPoint" type="xsd:string"/>
                    <xsd:element name="obsoletes" type="obsoleteTestCasesType" minOccurs="0"/>
                  </xsd:sequence>
                  <xsd:attribute name="version" type="xsd:string"/>
               </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="obsoleteTestCasesType">
        <xsd:sequence>
            <xsd:element name="testCase" type="xsd:string" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType> 
        
    <xsd:complexType name="relatedToType">
        <xsd:sequence>
            <xsd:element name="section" type="sectionType" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>  
    
    <xsd:complexType name="sectionType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="ver" type="xsd:string"/>
                <xsd:attribute name="how" type="xsd:string"/>
            </xsd:extension>
        </xsd:simpleContent> 
    </xsd:complexType>  
<!--    
    <xsd:complexType name="testCaseApplicabilityType">
        <xsd:sequence>
            <xsd:element name="XForms1.0" type="xsd:boolean"/>
            <xsd:element name="XForms1.1" type="xsd:boolean"/>  
        </xsd:sequence>
    </xsd:complexType>
-->
    <xsd:simpleType name="testCaseStatusType">
       <xsd:restriction base="xsd:string">
       	<xsd:enumeration value="Passed"/>
       	<xsd:enumeration value="Failed"/>
       	<xsd:enumeration value="Unknown"/>
       </xsd:restriction>
     </xsd:simpleType>    
	
</xsd:schema>

=== AlainCouthures/xsltforms/testsuite/XForms1.1/Edition1/driverPages/Results/XF11TestSuiteAppxH_Results.xml
<testSuite xmlns="http://www.w3c.org/MarkUp/Forms/XForms/Test/11" xsi:schemaLocation="http://www.w3c.org/MarkUp/Forms/XForms/Test/11 XF11TestSuite.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" specVersion="1.1">
    <specChapter chapterName="H. " productId="XSLTForms 1.0" chapterTitle="Complete XForms Examples">
        <statusSummary>
            <numNormTotal>0</numNormTotal>
            <numNormPass>0</numNormPass>
            <numNormFail>0</numNormFail>
            <numNormUnknown>0</numNormUnknown>
            <numBasicTotal>0</numBasicTotal>
            <numBasicPass>0</numBasicPass>
            <numBasicFail>0</numBasicFail>
            <numBasicUnknown>0</numBasicUnknown>
        </statusSummary>
        <profile>
            <specification>XForms 1.1</specification>
            <normativeOnly>false</normativeOnly>
            <basicOnly>false</basicOnly>
        </profile>
        <testCase>
            <testCaseSection>H.1</testCaseSection>
            <testCaseName>H.1</testCaseName>
            <testCaseLink>../../Appendix/H/h.1.xhtml</testCaseLink>
            <testCaseDescription>XForms in XHTML</testCaseDescription>
            <testCaseSpecLinkName>H.1</testCaseSpecLinkName>
            <testCaseSpecLink>http://www.w3.org/TR/xforms11/#xforms-in-xhtml-00</testCaseSpecLink>
            <testCaseBasic>false</testCaseBasic>
            <testCaseNormative>false</testCaseNormative>
            <testCaseStatus>Passed</testCaseStatus>
            <testCaseDate>2014-02-08</testCaseDate>
            <testCaseRequired>false</testCaseRequired>
            <testCaseNote/>
        </testCase>
        <testCase>
            <testCaseSection>H.2</testCaseSection>
            <testCaseName>H.2</testCaseName>
            <testCaseLink>../../Appendix/H/h.2.xhtml</testCaseLink>
            <testCaseDescription>Editing Hierarchical Bookmarks Using XForms</testCaseDescription>
            <testCaseSpecLinkName>H.2</testCaseSpecLinkName>
            <testCaseSpecLink>http://www.w3.org/TR/xforms11/#bookmarks-in-x-smiles</testCaseSpecLink>
            <testCaseBasic>false</testCaseBasic>
            <testCaseNormative>false</testCaseNormative>
            <testCaseStatus>Passed</testCaseStatus>
            <testCaseDate>2014-02-08</testCaseDate>
            <testCaseRequired>false</testCaseRequired>
            <testCaseNote/>
        </testCase>        
        <testCase>
            <testCaseSection>H.3</testCaseSection>
            <testCaseName>H.3</testCaseName>
            <testCaseLink>../../Appendix/H/h.3.svg</testCaseLink>
            <testCaseDescription>Survey Using XForms and SVG</testCaseDescription>
            <testCaseSpecLinkName>H.3</testCaseSpecLinkName>
            <testCaseSpecLink>http://www.w3.org/TR/xforms11/#N93686</testCaseSpecLink>
            <testCaseBasic>false</testCaseBasic>
            <testCaseNormative>false</testCaseNormative>
            <testCaseStatus>Failed</testCaseStatus>
            <testCaseDate>2014-02-08</testCaseDate>
            <testCaseRequired>false</testCaseRequired>
            <testCaseNote>SVG as host not supported</testCaseNote>
        </testCase>
    </specChapter>
</testSuite>

=== AlainCouthures/xsltforms/testsuite/XForms1.1/Edition1/driverPages/Results/XF11TestSuiteAppxG_Results.xml
<testSuite xmlns="http://www.w3c.org/MarkUp/Forms/XForms/Test/11" xsi:schemaLocation="http://www.w3c.org/MarkUp/Forms/XForms/Test/11 XF11TestSuite.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" specVersion="1.1">
    <specChapter chapterName="G. " productId="XSLTForms 1.0" chapterTitle="XForms and Styling">
        <statusSummary>
            <numNormTotal>0</numNormTotal>
            <numNormPass>0</numNormPass>
            <numNormFail>0</numNormFail>
            <numNormUnknown>0</numNormUnknown>
            <numBasicTotal>0</numBasicTotal>
            <numBasicPass>0</numBasicPass>
            <numBasicFail>0</numBasicFail>
            <numBasicUnknown>0</numBasicUnknown>
        </statusSummary>
        <profile>
            <specification>XForms 1.1</specification>
            <normativeOnly>false</normativeOnly>
            <basicOnly>false</basicOnly>
        </profile>
        <testCase>
            <testCaseSection>G.1</testCaseSection>
            <testCaseName>G.1.a</testCaseName>
            <testCaseLink>../../Appendix/G/G.1/g.1.a.xhtml</testCaseLink>
            <testCaseDescription>enabled and disabled pseudo-classes</testCaseDescription>
            <testCaseSpecLinkName>G.1</testCaseSpecLinkName>
            <testCaseSpecLink>http://www.w3.org/TR/xforms11/#N93414</testCaseSpecLink>
            <testCaseBasic>false</testCaseBasic>
            <testCaseNormative>false</testCaseNormative>
            <testCaseStatus>Passed</testCaseStatus>
            <testCaseDate>2014-02-08</testCaseDate>
            <testCaseRequired>false</testCaseRequired>
            <testCaseNote/>
        </testCase>
        <testCase>
            <testCaseSection>G.1</testCaseSection>
            <testCaseName>G.1.b</testCaseName>
            <testCaseLink>../../Appendix/G/G.1/g.1.b.xhtml</testCaseLink>
            <testCaseDescription>required and optional pseudo-classes</testCaseDescription>
            <testCaseSpecLinkName>G.1</testCaseSpecLinkName>
            <testCaseSpecLink>http://www.w3.org/TR/xforms11/#N93414</testCaseSpecLink>
            <testCaseBasic>false</testCaseBasic>
            <testCaseNormative>false</testCaseNormative>
            <testCaseStatus>Failed</testCaseStatus>
            <testCaseDate>2014-02-08</testCaseDate>
            <testCaseRequired>false</testCaseRequired>
            <testCaseNote/>
        </testCase>
        <testCase>
            <testCaseSection>G.1</testCaseSection>
            <testCaseName>G.1.c</testCaseName>
            <testCaseLink>../../Appendix/G/G.1/g.1.c.xhtml</testCaseLink>
            <testCaseDescription>valid and invalid pseudo-classes</testCaseDescription>
            <testCaseSpecLinkName>G.1</testCaseSpecLinkName>
            <testCaseSpecLink>http://www.w3.org/TR/xforms11/#N93414</testCaseSpecLink>
            <testCaseBasic>false</testCaseBasic>
            <testCaseNormative>false</testCaseNormative>
            <testCaseStatus>Failed</testCaseStatus>
            <testCaseDate>2014-02-08</testCaseDate>
            <testCaseRequired>false</testCaseRequired>
            <testCaseNote/>
        </testCase>
        <testCase>
            <testCaseSection>G.1</testCaseSection>
            <testCaseName>G.1.d</testCaseName>
            <testCaseLink>../../Appendix/G/G.1/g.1.d.xhtml</testCaseLink>
            <testCaseDescription>read-only and read-write pseudo-classes</testCaseDescription>
            <testCaseSpecLinkName>G.1</testCaseSpecLinkName>
            <testCaseSpecLink>http://www.w3.org/TR/xforms11/#N93414</testCaseSpecLink>
            <testCaseBasic>false</testCaseBasic>
            <testCaseNormative>false</testCaseNormative>
            <testCaseStatus>Failed</testCaseStatus>
            <testCaseDate>2014-02-08</testCaseDate>
            <testCaseRequired>false</testCaseRequired>
            <testCaseNote/>
        </testCase>
        <testCase>
            <testCaseSection>G.1</testCaseSection>
            <testCaseName>G.1.e</testCaseName>
            <testCaseLink>../../Appendix/G/G.1/g.1.e.xhtml</testCaseLink>
            <testCaseDescription>out-of-range and in-range pseudo-classes</testCaseDescription>
            <testCaseSpecLinkName>G.1</testCaseSpecLinkName>
            <testCaseSpecLink>http://www.w3.org/TR/xforms11/#N93414</testCaseSpecLink>
            <testCaseBasic>false</testCaseBasic>
            <testCaseNormative>false</testCaseNormative>
            <testCaseStatus>Failed</testCaseStatus>
            <testCaseDate>2014-02-08</testCaseDate>
            <testCaseRequired>false</testCaseRequired>
            <testCaseNote/>
        </testCase>
        <testCase>
            <testCaseSection>G.2</testCaseSection>
            <testCaseName>G.2.a</testCaseName>
            <testCaseLink>../../Appendix/G/G.2/g.2.a.xhtml</testCaseLink>
            <testCaseDescription>value pseudo-element</testCaseDescription>
            <testCaseSpecLinkName>G.2</testCaseSpecLinkName>
            <testCaseSpecLink>http://www.w3.org/TR/xforms11/#N93548</testCaseSpecLink>
            <testCaseBasic>false</testCaseBasic>
            <testCaseNormative>false</testCaseNormative>
            <testCaseStatus>Failed</testCaseStatus>
            <testCaseDate>2014-02-08</testCaseDate>
            <testCaseRequired>false</testCaseRequired>
            <testCaseNote/>
        </testCase>
        <testCase>
            <testCaseSection>G.2</testCaseSection>
            <testCaseName>G.2.b</testCaseName>
            <testCaseLink>../../Appendix/G/G.2/g.2.b.xhtml</testCaseLink>
            <testCaseDescription>repeat-item pseudo-element</testCaseDescription>
            <testCaseSpecLinkName>G.2</testCaseSpecLinkName>
            <testCaseSpecLink>http://www.w3.org/TR/xforms11/#N93548</testCaseSpecLink>
            <testCaseBasic>false</testCaseBasic>
            <testCaseNormative>false</testCaseNormative>
            <testCaseStatus>Failed</testCaseStatus>
            <testCaseDate>2014-02-08</testCaseDate>
            <testCaseRequired>false</testCaseRequired>
            <testCaseNote/>
        </testCase>
        <testCase>
            <testCaseSection>G.2</testCaseSection>
            <testCaseName>G.2.c</testCaseName>
            <testCaseLink>../../Appendix/G/G.2/g.2.c.xhtml</testCaseLink>
            <testCaseDescription>repeat-index pseudo-element</testCaseDescription>
            <testCaseSpecLinkName>G.2</testCaseSpecLinkName>
            <testCaseSpecLink>http://www.w3.org/TR/xforms11/#N93548</testCaseSpecLink>
            <testCaseBasic>false</testCaseBasic>
            <testCaseNormative>false</testCaseNormative>
            <testCaseStatus>Failed</testCaseStatus>
            <testCaseDate>2014-02-08</testCaseDate>
            <testCaseRequired>false</testCaseRequired>
            <testCaseNote/>
        </testCase>
        <testCase>
            <testCaseSection>G.2</testCaseSection>
            <testCaseName>G.2.d</testCaseName>
            <testCaseLink>../../Appendix/G/G.2/g.2.d.xhtml</testCaseLink>
            <testCaseDescription>repeat-index precedence over repeat-item</testCaseDescription>
            <testCaseSpecLinkName>G.2</testCaseSpecLinkName>
            <testCaseSpecLink>http://www.w3.org/TR/xforms11/#N93548</testCaseSpecLink>
            <testCaseBasic>false</testCaseBasic>
            <testCaseNormative>false</testCaseNormative>
            <testCaseStatus>Failed</testCaseStatus>
            <testCaseDate>2014-02-08</testCaseDate>
            <testCaseRequired>false</testCaseRequired>
            <testCaseNote/>
        </testCase>
    </specChapter>
</testSuite>

=== AlainCouthures/xsltforms/testsuite/XForms1.1/Edition1/driverPages/xml/XF11TestSuiteChpt2.xml
<?xml version="1.0" encoding="UTF-8"?>
<testSuite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3c.org/MarkUp/Forms/XForms/Test/11 XF11TestSuite.xsd" specVersion="1.1"
    xmlns="http://www.w3c.org/MarkUp/Forms/XForms/Test/11">
    <specChapter chapterName="2. " productId="" chapterTitle="Introduction to XForms">
        <statusSummary>
            <numNormTotal>0</numNormTotal>
            <numNormPass>0</numNormPass>
            <numNormFail>0</numNormFail>
            <numNormUnknown>0</numNormUnknown>
            <numBasicTotal>0</numBasicTotal>
            <numBasicPass>0</numBasicPass>
            <numBasicFail>0</numBasicFail>
            <numBasicUnknown>0</numBasicUnknown>
        </statusSummary>
        <profile>
            <specification>XForms 1.1</specification>
            <normativeOnly>false</normativeOnly>
            <basicOnly>false</basicOnly>
        </profile>
        <testCase>
            <testCaseSection>2.1</testCaseSection>
            <testCaseName>2.1.a</testCaseName>
            <testCaseLink>../../Chapt02/2.1.a.xhtml</testCaseLink>
            <testCaseDescription>Introductory Example No. 1</testCaseDescription>
            <testCaseSpecLinkName>2.1</testCaseSpecLinkName>
            <testCaseSpecLink>http://www.w3.org/TR/xforms11/#concepts-xhtml</testCaseSpecLink>
            <testCaseBasic>true</testCaseBasic>
            <testCaseNormative>true</testCaseNormative>
            <testCaseStatus>Unknown</testCaseStatus>
            <testCaseDate>2005-09-10</testCaseDate>
            <testCaseRequired>true</testCaseRequired>
            <testCaseNote />
        </testCase>
        <testCase>
            <testCaseSection>2.2</testCaseSection>
            <testCaseName>2.2.a</testCaseName>
            <testCaseLink>../../Chapt02/2.2.a.xhtml</testCaseLink>
            <testCaseDescription>Example: Encapsulation of Instance Data</testCaseDescription>
            <testCaseSpecLinkName>2.2</testCaseSpecLinkName>
            <testCaseSpecLink>http://www.w3.org/TR/xforms11/#concepts-xml-instance-data</testCaseSpecLink>
            <testCaseBasic>true</testCaseBasic>
            <testCaseNormative>true</testCaseNormative>
            <testCaseStatus>Unknown</testCaseStatus>
            <testCaseDate>2005-09-10</testCaseDate>
            <testCaseRequired>true</testCaseRequired>
            <testCaseNote />
        </testCase>
        <testCase>
            <testCaseSection>2.3</testCaseSection>
            <testCaseName>2.3.a</testCaseName>
            <testCaseLink>../../Chapt02/2.3.a.xhtml</testCaseLink>
            <testCaseDescription>Example: Value Constraints</testCaseDescription>
            <testCaseSpecLinkName>2.3</testCaseSpecLinkName>
            <testCaseSpecLink>http://www.w3.org/TR/xforms11/#concepts-model</testCaseSpecLink>
            <testCaseBasic>false</testCaseBasic>
            <testCaseNormative>true</testCaseNormative>
            <testCaseStatus>Unknown</testCaseStatus>
            <testCaseDate>2005-09-10</testCaseDate>
            <testCaseRequired>true</testCaseRequired>
            <testCaseNote />
        </testCase>
        <testCase>
            <testCaseSection>2.4</testCaseSection>
            <testCaseName>2.4.a</testCaseName>
            <testCaseLink>../../Chapt02/2.4.a.xhtml</testCaseLink>
            <testCaseDescription>Example: Multiple Forms</testCaseDescription>
            <testCaseSpecLinkName>2.4</testCaseSpecLinkName>
            <testCaseSpecLink>http://www.w3.org/TR/xforms11/#concepts-multiple</testCaseSpecLink>
            <testCaseBasic>false</testCaseBasic>
            <testCaseNormative>true</testCaseNormative>
            <testCaseStatus>Unknown</testCaseStatus>
            <testCaseDate>2005-09-10</testCaseDate>
            <testCaseRequired>true</testCaseRequired>
            <testCaseNote />
        </testCase>
    </specChapter>
</testSuite>
